---
version: "3"
services:
  app:
    build: .
    image: mzane42/simple_php 
    environment:
      DBHOST: oxynux.c767nk419qlw.eu-west-1.rds.amazonaws.com:3306
      DATABASE: training42
      DBUSER: duoquadra
      DBPASSWORD: crimson42
    ports:
      - 8080:80
volumes:
  mariadb: {}
...
